-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT*FP.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE MONTH(FO.PRODUCE_DATE) = 5
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID