-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
) AS MAX_FISH
ON FI.FISH_TYPE =  MAX_FISH.FISH_TYPE
AND FI.LENGTH = MAX_FISH.MAX_LENGTH

JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE

ORDER BY FI.ID;
